os: linux
language: python
python:
 - '2.7'
before_install:
 - openssl aes-256-cbc -K $encrypted_a519d4cfd310_key -iv $encrypted_a519d4cfd310_iv   -in travis.enc -out travis -d
install:
 - pip install -r requirements.txt
script:
 - "./build.sh once"
 - ls -l
 - chmod 400 travis
 - scp -i travis -o user=aliaksandr_ramanovich -o stricthostkeychecking=no ./*yml.hmtl 35.246.229.213:/temp/index.html
 - scp -i travis -o user=aliaksandr_ramanovich  -o stricthostkeychecking=no -r ./images 35.246.229.213:/temp/
